server.port=8080
spring.application.name=VeriLedger
# CORS Configurations
allowed.origins=http://localhost:5173

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
# Blockchain Setup
blockchain.rpc.url=https://ethereum-sepolia-rpc.publicnode.com
blockchain.contract.address=0x3903588c5Ed293E54304DD3d037dDE9e2907dEa9
blockchain.private.key=0x15b8377a15b3925abd7122e163ae99c3b9ddff8475889bdef1169cf7a92313d6
# Sepolia Testnet ID for EIP-155
blockchain.chain.id=11155111

# Auth
jwt.secret=veriledger-super-secret-key-minimum-32-chars-long-2026
google.client.id=178702966827-5g4st8snnunci0qtu2gdq36ljbaoe0es.apps.googleusercontent.com

